### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by Dievale** [Joaotcs/Hackintosh-Elitebook-8x0-g5#5] opened 2020-12-27 15:01 UTC
Hi coming from Kecincer AC lid discussion.
Thank you for all your work and help guys. I've tried the new EFI but Im having the same issue mentioned by Ermac. The trackpad from kecinzer EFI works perfect but as soon as I put your EFI I have no trackpad. the sound closing the lid is gone and touch screen works perfect.
Could you please advice what can I do or how to troubleshoot? Thank you

**Comment by Joaotcs** [comment] 2020-12-27 16:21
Hello!
That's impossible.. 
Kecinzer was using my acpi patch for touchpad... 
Are you sure you didn't change anything?

**Comment by Joaotcs** [comment] 2020-12-27 16:29
reset NVRAM on opencore... I have no modifications on trackpad side from kecinzer (he was using my patch).

**Comment by Joaotcs** [comment] 2020-12-27 16:33
Hello! Sorry, I checked again, the problem was that I forgot to add a kext!
It should be working now

**Comment by Dievale** [comment] 2020-12-27 16:39
Thank you very much for your help and prompt response. Confirmed that is working now.
Did you know why the HD camera also is not working or what can I do to troubleshoot?
I have an HP elitebook 840 G5 Intel HD graphic 620 7300u. Is there an easy way to dump the dsdt? Sorry Im a noob.
Thanks again

**Comment by Joaotcs** [comment] 2020-12-27 16:40
About camera you can forget. It either work or not. There is no workaround (there are different hardware)... You have to buy an external webcam to use when needed.

**Comment by Joaotcs** [comment] 2020-12-27 16:50
closing as the issue is fixed

**Closed as completed** 2020-12-27 16:50 UTC
